application: dori-udacity-cs253
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /static
  static_dir: static

- url: /.*
  script: dori-udacity-cs253.app

libraries:
- name: jinja2
  version: latest

- name: PIL
  version: "1.1.7"
